name: funds-ml-lstm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - tqdm
  - pyarrow
  - lightgbm
  - xgboost
  - statsmodels
  - pip
  - pip:
      - tensorflow==2.21.0
